Feature/create pop ups
AnaIoramashvili/QuizApp pull request #3
Opened 2024-11-19 12:53 UTC by AnaIoramashvili

2024-11-19 13:52 UTC, tamokakhidze reviewed
Few suggestions. But it is totally up to you

2024-11-19 13:52 UTC, tamokakhidze commented on QuizApp/Custom/CustomPopUp.swift
> +        label.font = .systemFont(ofSize: Constants.FontSize.medium, weight: .bold)
```suggestion
        label.font = .systemFont(
        ofSize: Constants.FontSize.medium, 
        weight: .bold
        )
```

2024-11-19 13:52 UTC, tamokakhidze commented on QuizApp/Custom/CustomPopUp.swift
> +        button.addTarget(self, action: #selector(handleNoButtonTap), for: .touchUpInside)
```suggestion
        button.addTarget(
        self, 
        action: #selector(handleNoButtonTap), 
        for: .touchUpInside
        )
```

2024-11-20 08:08 UTC, LukaGujejiani requested changes

2024-11-20 08:08 UTC, LukaGujejiani commented on QuizApp/Custom/CustomPopUp.swift
> +    private func setConstraints() {
Function is just calling another function and nothing more

2024-11-21 10:56 UTC, AnaIoramashvili commented on QuizApp/Custom/CustomPopUp.swift
> +        label.font = .systemFont(ofSize: Constants.FontSize.medium, weight: .bold)
I prefer label.font = .systemFont(ofSize: Constants.FontSize.medium, weight: .bold) this styling

2024-11-25 13:10 UTC, AniDzamelashvili approved these changes

2024-11-25 13:10 UTC, AniDzamelashvili commented on QuizApp/Custom/CustomPopUp.swift
> +        button.addTarget(self, action: #selector(handleNoButtonTap), for: .touchUpInside)
it is marked as resolved but suggestion is still not applied

2024-11-25 13:40 UTC, LukaGujejiani approved these changes

2024-11-25 13:42 UTC, tamokakhidze approved these changes

2024-11-25 13:45 UTC, merged